name: Unpack ZIP and Commit

on:
  push:
    paths:
      - 'evil-party-clean-flat.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Unzip project
        run: unzip evil-party-clean-flat.zip

      - name: Commit unzipped files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Unpack project ZIP"
          git push
